declare const _exports: {
    isError: typeof errors.isError;
    isCallException: typeof errors.isCallException;
    makeError: typeof errors.makeError;
    assert: typeof errors.assert;
    assertArgument: typeof errors.assertArgument;
    ProviderError: typeof errors.ProviderError;
    TransactionError: typeof errors.TransactionError;
    ContractError: typeof errors.ContractError;
    formatUnits: typeof import("./utils/units").formatUnits;
    parseUnits: typeof import("./utils/units").parseUnits;
    formatEther: typeof import("./utils/units").formatEther;
    parseEther: typeof import("./utils/units").parseEther;
    WeiPerEther: bigint;
    Result: typeof import("./utils/result").Result;
    checkResultErrors: typeof import("./utils/result").checkResultErrors;
    encodeRlp: typeof import("./utils/rlp").encodeRlp;
    decodeRlp: typeof import("./utils/rlp").decodeRlp;
    keccak256: typeof import("./utils/hashing").keccak256;
    sha256: typeof import("./utils/hashing").sha256;
    sha512: typeof import("./utils/hashing").sha512;
    ripemd160: typeof import("./utils/hashing").ripemd160;
    id: typeof import("./utils/hashing").id;
    randomBytes: typeof import("./utils/hashing").randomBytes;
    computeHmac: typeof import("./utils/hashing").computeHmac;
    pbkdf2: typeof import("./utils/hashing").pbkdf2;
    scrypt: typeof import("./utils/hashing").scrypt;
    scryptSync: typeof import("./utils/hashing").scryptSync;
    toUtf8String: typeof import("./utils/encoding").toUtf8String;
    toUtf8Bytes: typeof import("./utils/encoding").toUtf8Bytes;
    toHex: typeof import("./utils/encoding").toHex;
    hexlify: typeof import("./utils/encoding").hexlify;
    arrayify: typeof import("./utils/encoding").arrayify;
    concat: typeof import("./utils/encoding").concat;
    stripZerosLeft: typeof import("./utils/encoding").stripZerosLeft;
    encodeBytes32String: typeof import("./utils/encoding").encodeBytes32String;
    decodeBytes32String: typeof import("./utils/encoding").decodeBytes32String;
    decodeBase58: typeof import("./utils/encoding").decodeBase58;
    decodeBase64: typeof import("./utils/encoding").decodeBase64;
    encodeBase58: typeof import("./utils/encoding").encodeBase58;
    encodeBase64: typeof import("./utils/encoding").encodeBase64;
    toUtf8CodePoints: typeof import("./utils/encoding").toUtf8CodePoints;
    isHexString: typeof import("./internal/hex").isHexString;
    isBytesLike: typeof import("./utils/encoding").isBytesLike;
    zeroPad: typeof import("./utils/encoding").zeroPad;
    zeroPadValue: typeof import("./utils/encoding").zeroPadValue;
    solidityPacked: typeof import("./utils/encoding").solidityPacked;
    solidityPackedKeccak256: typeof import("./utils/encoding").solidityPackedKeccak256;
    solidityPackedSha256: typeof import("./utils/encoding").solidityPackedSha256;
    bytesToHex: typeof import("./internal/hex").bytesToHex;
    hexToBytes: typeof import("./internal/hex").hexToBytes;
    isAddress: typeof import("./utils/address").isAddress;
    getAddress: typeof import("./utils/address").getAddress;
    isAddressable: typeof import("./utils/address").isAddressable;
    resolveAddress: typeof import("./utils/address").resolveAddress;
    getContractAddress: typeof import("./utils/address").getContractAddress;
    getCreateAddress: typeof import("./utils/address").getCreateAddress;
    getCreate2Address: typeof import("./utils/address").getCreate2Address;
    computeAddress: typeof import("./utils/address").computeAddress;
    verifyMessage: typeof import("./utils/address").verifyMessage;
    recoverAddress: typeof import("./utils/address").recoverAddress;
    Interface: typeof import("./abi/interface").Interface;
    AbiCoder: typeof import("./abi/interface").AbiCoder;
    Fragment: typeof import("./abi/fragments").Fragment;
    NamedFragment: typeof import("./abi/fragments").NamedFragment;
    FunctionFragment: typeof import("./abi/fragments").FunctionFragment;
    EventFragment: typeof import("./abi/fragments").EventFragment;
    ErrorFragment: typeof import("./abi/fragments").ErrorFragment;
    ConstructorFragment: typeof import("./abi/fragments").ConstructorFragment;
    StructFragment: typeof import("./abi/fragments").StructFragment;
    FallbackFragment: typeof import("./abi/fragments").FallbackFragment;
    ContractFactory: typeof import("./contract/contract-factory").ContractFactory;
    BaseContract: typeof import("./contract/contract").BaseContract;
    Contract: typeof import("./contract/contract").Contract;
    ContractTransactionResponse: typeof import("./contract/contract").ContractTransactionResponse;
    ContractTransactionReceipt: typeof import("./contract/contract").ContractTransactionReceipt;
    EventLog: typeof import("./contract/contract").EventLog;
    SigningKey: typeof import("./wallet/wallet").SigningKey;
    AbstractSigner: typeof import("./wallet/wallet").AbstractSigner;
    BaseWallet: typeof import("./wallet/wallet").BaseWallet;
    Wallet: typeof import("./wallet/wallet").Wallet;
    NonceManager: typeof import("./wallet/wallet").NonceManager;
    JsonRpcSigner: typeof import("./wallet/wallet").JsonRpcSigner;
    VoidSigner: typeof import("./wallet/wallet").VoidSigner;
    WebSocketProvider: typeof import("./providers/extra-providers").WebSocketProvider;
    IpcSocketProvider: typeof import("./providers/extra-providers").IpcSocketProvider;
    BrowserProvider: typeof import("./providers/extra-providers").BrowserProvider;
    FallbackProvider: typeof import("./providers/extra-providers").FallbackProvider;
    FilterByBlockHash: typeof import("./providers/extra-providers").FilterByBlockHash;
    JsonRpcProvider: typeof import("./providers/json-rpc-provider").JsonRpcProvider;
    JsonRpcApiProvider: typeof import("./providers/json-rpc-provider").JsonRpcApiProvider;
    Provider: typeof import("./providers/provider").Provider;
    AbstractProvider: typeof import("./providers/provider").AbstractProvider;
    Block: typeof import("./providers/provider").Block;
    TransactionResponse: typeof import("./providers/provider").TransactionResponse;
    TransactionReceipt: typeof import("./providers/provider").TransactionReceipt;
    Log: typeof import("./providers/provider").Log;
    version: string;
    ZeroAddress: string;
    ZeroHash: string;
    MaxUint256: bigint;
    MaxUint160: bigint;
    MinInt256: bigint;
    MaxInt256: bigint;
    NumericFault: string;
    NumericFaultCode: string;
    EtherSymbol: string;
    N: bigint;
};
export = _exports;
import errors = require("./errors");

// ---------------------------------------------------------------------------
// Core Solidity typing exports (type-only)
// ---------------------------------------------------------------------------
declare namespace _exports {
    export type AddressLike = import("./types").AddressLike;
    export type BytesLike = import("./types").BytesLike;
    export type Bytes32Like = import("./types").Bytes32Like;
    export type BigNumberish = import("./types").BigNumberish;
    export type HexString = import("./types").HexString;
    export type SolidityTypeName = import("./types").SolidityTypeName;
    export type SolidityInputValue<T extends SolidityTypeName> = import("./types").SolidityInputValue<T>;
    export type SolidityOutputValue<T extends SolidityTypeName> = import("./types").SolidityOutputValue<T>;
    export type SolidityTuple = import("./types").SolidityTuple;
    export type SolidityStruct = import("./types").SolidityStruct;
}
