name: Generate Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src.ts/**"
      - "docs.wrm/**"

jobs:
  docs:
    name: Generate Documentation

    runs-on: ubuntu-latest

    environment: ethers-tests

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Install dependencies
        run: npm ci

      - name: Install Flatworm
        run: npm install --no-save 'https://github.com/ricmoo/flatworm.git#tsdocs'

      - name: Build Documentation
        run: node node_modules/flatworm/lib/cli-test ./docs.wrm/config.mjs

      - name: Show Docs
        run: ls output/docs/


