name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: npm

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Install TypeScript
        run: npm install --g typescript

      - name: Build distribution
        run: |
          npm run build-all
          npm run build-dist
          ls
          pwd

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: quantumcoin
          path: |
            ${{ github.workspace }}/dist/*.*

      - name: release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "dist/*.*"
